auteur = "Gertrude Atherton"
author = "Gertrude Atherton"
bloctexte = "justify"
copyright = "CC BY-NC-SA"
couverture = "/uploads/couverture.png"
description = "horror short story"
edition = "Fabrique"
format = "portrait"
indentation = "oui"
isbn = ""
licence = "CC BY-NC-SA"
logo = "images/logo.jpg"
marques = "crop"
mention = "Fabrique"
quatrieme = "oui"
readingtime = "oui"
search = false
soustitre = ""
titre = "The Bell in the Fog"
date = "Originally published in 1905. Wikidata version last edited on 30 December 2020, at 19:47."
